// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJCX40XVkCM7z-RCqNmr4iphu8KyPMS8',
    appId: '1:1088509430521:web:c3667190234af1a16a3028',
    messagingSenderId: '1088509430521',
    projectId: 'writefolio-65a1a',
    authDomain: 'writefolio-65a1a.firebaseapp.com',
    storageBucket: 'writefolio-65a1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNoSNSE_ShI5k1heyvgDELbd3UXK10CdE',
    appId: '1:1088509430521:android:16da36541c26b57c6a3028',
    messagingSenderId: '1088509430521',
    projectId: 'writefolio-65a1a',
    storageBucket: 'writefolio-65a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQzhJ9Qmklfd5BMHiYAVOQTQM6pbkzxJ8',
    appId: '1:1088509430521:ios:4971924f34aaa0696a3028',
    messagingSenderId: '1088509430521',
    projectId: 'writefolio-65a1a',
    storageBucket: 'writefolio-65a1a.appspot.com',
    iosClientId: '1088509430521-doptkm4hq5m7vrcoisv2icmsi15ku747.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediumClient',
  );
}
